In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [23]:
df=pd.read_csv(r"C:\Users\HP\Documents\Zalo Received Files\Data\Advertising.csv")

In [24]:
X=np.array([np.ones(n).T,df.TV.values,df.Radio.values,df.Newspaper.values]).T
y=df.Sales.values

In [25]:
X.shape

(200, 4)

In [26]:
y.shape

(200,)

In [27]:
beta=np.dot(np.linalg.inv(np.dot(X.T,X)),np.dot(X.T,y))
beta

array([ 2.93888937e+00,  4.57646455e-02,  1.88530017e-01, -1.03749304e-03])

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((160, 4), (40, 4), (160,), (40,))

In [31]:
linear = LinearRegression()
linear.fit(X_train,y_train)

LinearRegression()

In [32]:
linear.predict(X_test)[:5]

array([16.4080242 , 20.88988209, 21.55384318, 10.60850256, 22.11237326])

In [33]:
y_test[:5]

array([16.9, 22.4, 21.4,  7.3, 24.7])

In [34]:
from sklearn.metrics import mean_squared_error

y_preds_test = linear.predict(X_test)
mse_test = mean_squared_error(y_test, y_preds_test)
mse_test

3.1740973539761077

In [35]:
y_preds2 = linear.predict(X_train)
mse_train = mean_squared_error(y_train, y_preds2)
mse_train

2.705129423081414

In [36]:
beta=np.dot(np.linalg.inv(np.dot(X_train.T,X_train)),np.dot(X_train.T,y_train))

print(beta.round(4))

[2.9791e+00 4.4700e-02 1.8920e-01 2.8000e-03]


Phuong trinh hoi quy 

$Sales = beta[0] + beta[1]*df.TV + beta[2]*df.Radio +beta[3]*df.Newspaper$

In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [38]:
df=pd.read_csv(r"C:\Users\HP\Documents\Zalo Received Files\Data\Credit.csv")

In [39]:
df.head()

Unnamed: 0   Income  Limit  Rating  Cards  Age  Education  Gender Student  \
0           1   14.891   3606     283      2   34         11    Male      No   
1           2  106.025   6645     483      3   82         15  Female     Yes   
2           3  104.593   7075     514      4   71         11    Male      No   
3           4  148.924   9504     681      3   36         11  Female      No   
4           5   55.882   4897     357      2   68         16    Male      No   

  Married  Ethnicity  Balance  
0     Yes  Caucasian      333  
1     Yes      Asian      903  
2      No      Asian      580  
3      No      Asian      964  
4     Yes  Caucasian      331

In [40]:
df["Gender"] = df["Gender"].map({" Male": 0, "Female": 1})


In [41]:
df["Student"] = df["Student"].map({"Yes": 1, "No": 0})

In [42]:
df["Married"] = df["Married"].map({"Yes": 1, "No": 0})
df.head()

Unnamed: 0   Income  Limit  Rating  Cards  Age  Education  Gender  Student  \
0           1   14.891   3606     283      2   34         11       0        0   
1           2  106.025   6645     483      3   82         15       1        1   
2           3  104.593   7075     514      4   71         11       0        0   
3           4  148.924   9504     681      3   36         11       1        0   
4           5   55.882   4897     357      2   68         16       0        0   

   Married  Ethnicity  Balance  
0        1  Caucasian      333  
1        1      Asian      903  
2        0      Asian      580  
3        0      Asian      964  
4        1  Caucasian      331

In [43]:
df["Ethnicity_Asian"] = df["Ethnicity"].map(lambda x: 1 if x == "Asian" else 0)
df["Ethnicity_Caucasian"] = df["Ethnicity"].map(lambda x: 1 if x == "Caucasian" else 0)

df = df.drop("Ethnicity", axis=1)
df.head()


Unnamed: 0   Income  Limit  Rating  Cards  Age  Education  Gender  Student  \
0           1   14.891   3606     283      2   34         11       0        0   
1           2  106.025   6645     483      3   82         15       1        1   
2           3  104.593   7075     514      4   71         11       0        0   
3           4  148.924   9504     681      3   36         11       1        0   
4           5   55.882   4897     357      2   68         16       0        0   

   Married  Balance  Ethnicity_Asian  Ethnicity_Caucasian  
0        1      333                0                    1  
1        1      903                1                    0  
2        0      580                1                    0  
3        0      964                1                    0  
4        1      331                0                    1

In [44]:
y = df['Balance']
X = df.drop('Balance', axis=1)

In [45]:
X.head()

X = X.drop('Unnamed: 0', axis=1)

In [46]:
X.head()

Income  Limit  Rating  Cards  Age  Education  Gender  Student  Married  \
0   14.891   3606     283      2   34         11       0        0        1   
1  106.025   6645     483      3   82         15       1        1        1   
2  104.593   7075     514      4   71         11       0        0        0   
3  148.924   9504     681      3   36         11       1        0        0   
4   55.882   4897     357      2   68         16       0        0        1   

   Ethnicity_Asian  Ethnicity_Caucasian  
0                0                    1  
1                1                    0  
2                1                    0  
3                1                    0  
4                0                    1

In [47]:
y.head()

0    333
1    903
2    580
3    964
4    331
Name: Balance, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split


In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X.shape, X_test.shape)

(400, 11) (80, 11)


In [51]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import r2_score, root_mean_squared_error
from sklearn.model_selection import cross_val_score


models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(),
    "Lasso Regression": Lasso(),
    "Random Forest": RandomForestRegressor()
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    rmse = root_mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    results[name] = {"RMSE": rmse, "R2": r2}


for name, res in results.items():
    print(f"{name}: R2 Score = {res['R2']:.4f}, RMSE = {res['RMSE']:.2f}")

f:\python3115\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.615e+06, tolerance: 7.097e+03
  model = cd_fast.enet_coordinate_descent(


Linear Regression: R2 Score = 0.9523, RMSE = 89.30
Ridge Regression: R2 Score = 0.9516, RMSE = 89.97
Lasso Regression: R2 Score = 0.9514, RMSE = 90.07
Random Forest: R2 Score = 0.9260, RMSE = 111.21


In [52]:
lr = models["Linear Regression"]
print("Phương trình hồi quy:")
print("y = {:.2f}".format(lr.intercept_), end="")
for i, col in enumerate(X_train.columns):
    print(" + ({:.2f} * {})".format(lr.coef_[i], col), end="")
print()

Phương trình hồi quy:
y = -465.05 + (-7.55 * Income) + (0.20 * Limit) + (0.97 * Rating) + (19.12 * Cards) + (-0.60 * Age) + (-1.08 * Education) + (-12.49 * Gender) + (418.44 * Student) + (-6.15 * Married) + (13.30 * Ethnicity_Asian) + (11.52 * Ethnicity_Caucasian)
